### PR TITLE
Adding a basic build system for the NodeJS tests

### PR DESCRIPTION
**Pull request by darthtrevino**
Build System:
No build system was in place, so I've added Grunt and an initial testing target. As the project is refactored we can augment this with more interesting build tasks.

Tests Runner:
The tests that are present are run in an ad-hoc fashion. I've wired the NodeJS specific tests into Grunt and 'npm test'. I've also updated the test framework from expresso to Mocha+ChaiJS.

Test Structure:
There were a few fixtures in-place for testing basic functionality common to all storage providers. I've combined these into a general store_implementation test fixture that generates a fixture per storage type. Concomitant to this is a set of storage-provider configuration files under the 'store_impl' directory.

Additional Notes:
I had to remove the sqlite tests. I was unable to npm-install the sqlite library, and it looks like it's been abandoned. It looks like most people have migrated to Sqlite3.

### CODE REVIEW

**Comment by darthtrevino** [comment]
The tests are definitely a WIP. I'll throw more pull requests your way as I migrate them over.

**Comment by TheCodeDestroyer** [comment]
@darthtrevino nice job. I only have one comment would you mind switching to vanilla js Gruntfile instead of coffee script?

**Comment by darthtrevino** [comment]
Added requested curly braces and semicolons. 

I also added JSHint to the build. Right now it's only linting the Gruntfile in the default task. One of the things we should tackle is fixing linting issues across the rest of the codebase.

**Comment by TheCodeDestroyer** [comment]
Sadly there are some conflicts now and I can't merge

**Comment by darthtrevino** [comment]
I'll check the conflicts in my shell. If the conflicts are trivial, I'm assuming you're okay with a :shipit: ?

**Comment by TheCodeDestroyer** [comment]
Sure

**Pull request merged**
